config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#index'
  resources :users do
    resources :questions
  end
  
  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  resources :questions do
    resources :answers
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  validates :answer, :presence => true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers

  validates :question, :presence => true
  validates :body, :presence => true
  after_create :send_question_confirmation

  default_scope { order(created_at: 'DESC') }

  def send_question_confirmation
    QuestionMailer.question_confirmation(self.user).deliver
  end



end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers

  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password
  after_create :send_welcome_message

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def send_welcome_message
    UserMailer.signup_confirmation(self).deliver
  end


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    if @answer.save
      current_user.answers.push(@answer)
      flash[:notice] = "Your answer has been posted."
      redirect_to user_question_path(current_user.id, @question)
    else
      render :new
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:answer)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end
  def show
    @user = User.find(params[:user_id])
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @user = current_user
    @question = current_user.questions.new(question_params)
    if @question.save
      flash[:notice] = "Your question has been posted."
      redirect_to '/'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @question = Question.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = "Your question has been updated."
      redirect_to user_question_path(@user, @question)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @question = Question.find(params[:id])
    @question.destroy
    flash[:notice] = "Your question has been deleted."
    redirect_to '/'
  end


  private

  def question_params
    params.require(:question).permit(:question, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to this site!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<%= render "layouts/errors", :object => @answer %>

<%= form_for [@question, @answer] do |f| %>
  <%= f.label :answer %>
  <%= f.text_field :answer %>
  <%= f.submit %>
<% end %>

app/views/answers/new.html.erb
<h1>Answer Question</h1>

<%= render 'form' %>

app/views/home/index.html.erb
<% if current_user != nil %>
  <%= link_to "Ask Question", new_user_question_path(current_user) %>
<% else %>
  <p>Log in to ask a question.</p>
<% end %>


<h2>Questions</h2>



<ul>
  <% Question.all.each do |question| %>
    <li><%= link_to question.question, user_question_path(question.user, question) %> --
    <small>Asked by: <%= question.user.email %></small></li>
    <hr>
  <% end %>
</ul>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Overflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <nav class="navbar navbar-inverse navbar-fixed-top" id="my-navbar">
      <div class="container">
        <div class="navbar-header">

          <button class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>

          <a href="/" class="navbar-brand">Overflow</a>

        </div>
         <div class="collapse navbar-collapse" id="navbar-collapse">



          <ul class="nav navbar-nav">
            <% if current_user == nil %>
              <li><%= link_to 'Log In', log_in_path %></li>
              <li><%= link_to 'Register', new_user_path %></li>

            <% else %>
              <li><%= link_to "Logged in as: #{current_user.email}", '/'  %></li>
              <li><%= link_to "Log Out", log_out_path %></li>

            <% end %>
          </ul>
        </div>

      </div>
    </nav>

  <div class="container">

    <%= flash[:notice] %>
    <%= flash[:alert] %>
    <br>


    <%= yield %>
  </div>

</body>
</html>

app/views/questions/_form.html.erb
<%= render "layouts/errors", :object => @question %>

<%= form_for [current_user, @question] do |f| %>
  <%= f.label :question %>
  <%= f.text_field :question %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<% if @question.user_id == current_user.id %>
  <%= render 'form' %>
<% else %>
  <h3>You must be the user who asked the question to edit it! CHEATER!</h3>
<% end %>

app/views/questions/new.html.erb
<h1>Ask Question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<h1><%= @question.question %></h1>

<h3><%= @question.body %></h3>

<h4>Asked by: <%= @question.user.email %></h4>

<% if current_user != nil %>
  <% if @question.user_id == current_user.id %>
    <%= link_to "Edit Question", edit_user_question_path(@user, @question) %>
    <%= link_to "Delete Question", user_question_path(@user, @question),
                                    :data => {:confirm => "Are you sure?",
                                              :method => 'delete'}%>
  <% end %>

  <%= link_to "Add answer", new_question_answer_path(@question, @answer) %>
  <ul>
    <% @question.answers.each do |answer| %>
      <li><%= answer.answer %> -- <small><%= answer.user.email %></small>
      </li>
      <hr>
    <% end %>
  </ul>


<% else %>
  <p>You must be logged in to view/add answers</p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for User.new do |f| %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<%= f.submit "Sign Up" %>
<% end %>